### ISSUE TITLE
Segmentation fault when no display is available

### ISSUE THREAD

**Issue by mdgaziur** [mebesus/sysfex#2]
Sysfex segfaults when a display is not available. For example, on tty there's no display. Try running it in a tty(Ctrl+Alt+F(n)). 

What happens probably is that when the display is null, X11Display returns nullptr instead of an actual pointer. And dereferencing that causes segfault. Solution is to check for null pointer and take action accordingly.

**Comment by mebesus** [comment]
Thanks for letting me know, I'll try to fix it soon

**Comment by mdgaziur** [comment]
shall I make a patch?

**Comment by mdgaziur** [comment]
#3
