### ISSUE TITLE
"std::filesystem has not been declared" installation error

### ISSUE THREAD

**Issue by MrHappyHam** [mebesus/sysfex#4]
I tried to install it on Ubuntu but it failed. Here's what was printed:

> #Compiling sysfex...
> In file included from src/sysfex.cpp:25:
> src/functions.h:14:37: warning: use of ‘auto’ in parameter declaration only available with ‘-fconcepts-ts’
>    14 | void print(string icon, string key, auto value)
>       |                                     ^~~~
> src/functions.h: In function ‘void init_config()’:
> src/functions.h:46:13: error: ‘std::filesystem’ has not been declared
>    46 |     if(std::filesystem::exists("/opt/sysfex/config"))
>       |             ^~~~~~~~~~
> src/functions.h: In function ‘std::string exec(const char*)’:
> src/functions.h:89:10: error: ‘unique_ptr’ is not a member of ‘std’
>    89 |     std::unique_ptr<FILE, decltype(&pclose)> stream{popen(input, "r"), &pclose};
>       |          ^~~~~~~~~~
> src/functions.h:1:1: note: ‘std::unique_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
>   +++ |+#include <memory>
>     1 | #define BOLD    "\033[1m"
> src/functions.h:89:25: error: expected primary-expression before ‘,’ token
>    89 |     std::unique_ptr<FILE, decltype(&pclose)> stream{popen(input, "r"), &pclose};
>       |                         ^
> src/functions.h:89:27: error: expected primary-expression before ‘decltype’
>    89 |     std::unique_ptr<FILE, decltype(&pclose)> stream{popen(input, "r"), &pclose};
>       |                           ^~~~~~~~~~~~~~~~~
> src/functions.h:91:8: error: ‘stream’ was not declared in this scope; did you mean ‘std::io_errc::stream’?
>    91 |     if(stream)
>       |        ^~~~~~
>       |        std::io_errc::stream
> In file included from /usr/include/c++/10/ios:42,
>                  from /usr/include/c++/10/ostream:38,
>                  from /usr/include/c++/10/iostream:39,
>                  from src/sysfex.cpp:2:
> /usr/include/c++/10/bits/ios_base.h:203:24: note: ‘std::io_errc::stream’ declared here
>   203 |   enum class io_errc { stream = 1 };
>       |                        ^~~~~~
> In file included from src/sysfex.cpp:26:
> src/fetch_functions.h: In function ‘int Pacman(std::string)’:
> src/fetch_functions.h:174:10: error: ‘std::filesystem’ has not been declared
>   174 |     std::filesystem::path pkgfolder = path;
>       |          ^~~~~~~~~~
> src/fetch_functions.h:175:16: error: ‘std::filesystem’ has not been declared
>   175 |     using std::filesystem::directory_iterator;
>       |                ^~~~~~~~~~
> src/fetch_functions.h:176:45: error: ‘pkgfolder’ was not declared in this scope
>   176 |     return std::distance(directory_iterator(pkgfolder), directory_iterator{});
>       |                                             ^~~~~~~~~
> src/fetch_functions.h:176:26: error: ‘directory_iterator’ was not declared in this scope
>   176 |     return std::distance(directory_iterator(pkgfolder), directory_iterator{});
>       |                          ^~~~~~~~~~~~~~~~~~
> src/fetch_functions.h:176:75: error: expected ‘)’ before ‘{’ token
>   176 |     return std::distance(directory_iterator(pkgfolder), directory_iterator{});
>       |                         ~                                                 ^
>       |                                                                           )
> src/fetch_functions.h: In function ‘int Portage(std::string)’:
> src/fetch_functions.h:181:10: error: ‘std::filesystem’ has not been declared
>   181 |     std::filesystem::path pkgfolder = path;
>       |          ^~~~~~~~~~
> src/fetch_functions.h:183:16: error: ‘std::filesystem’ has not been declared
>   183 |     using std::filesystem::recursive_directory_iterator;
>       |                ^~~~~~~~~~
> src/fetch_functions.h:184:16: error: ‘recursive_directory_iterator’ was not declared in this scope
>   184 |     for(auto i=recursive_directory_iterator(path); i!=recursive_directory_iterator(); ++i)
>       |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> src/fetch_functions.h: In function ‘void pkgs()’:
> src/fetch_functions.h:201:13: error: ‘std::filesystem’ has not been declared
>   201 |     if(std::filesystem::exists("/etc/portage"))
>       |             ^~~~~~~~~~
> src/fetch_functions.h:205:13: error: ‘std::filesystem’ has not been declared
>   205 |     if(std::filesystem::exists("/etc/pacman.d"))
>       |             ^~~~~~~~~~
> src/fetch_functions.h:209:13: error: ‘std::filesystem’ has not been declared
>   209 |     if(std::filesystem::exists("/etc/apt"))
>       |             ^~~~~~~~~~
> src/fetch_functions.h:213:13: error: ‘std::filesystem’ has not been declared
>   213 |     if(std::filesystem::exists("/nix"))
>       |             ^~~~~~~~~~
> src/fetch_functions.h:215:17: error: ‘std::filesystem’ has not been declared
>   215 |         if(std::filesystem::exists("/etc/nix"))
>       |                 ^~~~~~~~~~
> An error occured. Failed to install sysfex

**Comment by mebesus** [comment]
Which version of g++ are you using? (check using ``g++ --version``)
Also, can you please tell me the output of this command: ``g++ src/sysfex.cpp -o sysfex -lX11 -lstdc++fs``
If this command makes sysfex compile successfully, I'll add the ``-lstdc++fs`` flag in the installer script.

**Comment by Spedzay** [comment]
I had the same issue, i solved it by using
`g++ src/sysfex.cpp -o sysfex -std=c++17 -lX11 -lstdc++fs`
any release after c++14 the filesystem issue goes away :)

**Comment by mebesus** [comment]
Ok thanks, I'll add this command in the installation script

**Comment by MrHappyHam** [comment]
That did the trick. Thanks, all!
