### ISSUE TITLE
Binary and Conf directory owned by Root when using `./install.sh`

### ISSUE THREAD

**Issue by JMuff22** [mebesus/sysfex#6]
Hi, just to let you know that I had some installation issues. The `sysfex` binary and the opt configure directory are both owned by root and therefore could not be run by a standard users. This was resolved with a simple `chown $USER /usr/bin/sysfex` however it should probably be within the install script.

This was done on Ubuntu 20.0.4 compiled using g++.

**Comment by mebesus** [comment]
Any updates with the latest commit?

**Comment by JMuff22** [comment]
Seems to be working! Thanks
